### ISSUE TITLE
Payout transaction from bridge PP

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/nervos#33]
# Bounty

![parentBridgeTxns (3)](https://user-images.githubusercontent.com/659301/92740200-d77d5c00-f37d-11ea-8651-c36730828f7f.png)

## Scope

- enable relay of [unlock receipt](https://github.com/leapdao/nervos/blob/master/docs/childchain.md#unlock) from child chain.
- require additional input to pay for transaction fee
- fork out withdrawn capacity into `auditDelay()` script, mock it if it doesn't exist yet.
- add `txHash` from receipt into data of contract, use it as lock to prevent payouts based on same hash.

## Deliverables

- code
- tests

## Funding Circle
Nervos

## Bounty Owner/Gardener

@johannbarbie 

## Roles
bounty gardener: @johannbarbie  / 15%
bounty worker: @Clearwood 37.5% /  @johannbarbie 37.5%
bounty reviewer: name / 10 %

## Gardener checklist

- [ ] I have attached one of the `size-` labels to this bounty
- [ ] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by Clearwood** [comment]
# Progress on payout tx from Bridge

## Done

- [x] State for Payout created
- [x] confirm that outputs don't have higher value than inputs
- [x] get validators from typescript
- [x] check that only one output has state id
- [x] check for deployed contract
- [x] get signature receipts from witness and verify format
- [x] check action byte of Witness

## TODO

- [ ] check that validator quorum is reached
- [ ] recover public key from signature, compare to validator set
- [ ] add txHash from receipt into data of contract, use it as lock to prevent payouts based on same hash.
- [ ] require additional input to pay for transaction fee

## TESTS

- [x] simple positive test case with one validator
- [ ] include or mock audit delay script in tests
- [ ] test cases with multiple validators
- [ ] negative test cases with incorrect signatures, not enough sigs, incorrect argument encoding, etc.

**Comment by Clearwood** [comment]
forked out into #57 and #58
